include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_constructors_first: true
    unawaited_futures: true

    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true

    # Documentation
    public_member_api_docs: false

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
